# Generated by Django 5.0.1 on 2024-01-15 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('movil_type', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('payment_day', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
