# Generated by Django 5.0.1 on 2024-01-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='movil_type',
            new_name='car_type',
        ),
    ]
