# Generated by Django 5.0.1 on 2024-01-21 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_movil_type_client_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_day',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(31)]),
        ),
    ]
