# Generated by Django 5.0.1 on 2024-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_remove_client_payment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_end',
            field=models.CharField(default='26/01', editable=False, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_start',
            field=models.CharField(default='26/02', editable=False, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='license_plate',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
