# Generated by Django 5.0.1 on 2024-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_client_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_end',
            field=models.CharField(editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_start',
            field=models.CharField(editable=False, max_length=5),
        ),
    ]
